service: benbeal-lyric-bot

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
functions:
  benbeal_lyric_bot:
    handler: handler.handler
    package:
      include:
        - ../../../node_modules
